version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/dev"
    schedule:
      interval: "daily"
    assignees:
      - "luisa-beerboom"
    groups:
      code-style-depedencies:
        patterns:
          - "autoflake"
          - "black"
          - "debugpy"
          - "flake8"
          - "isort"
          - "mypy"
          - "pyupgrade"
      web-dependencies:
        patterns:
          - "requests"
          - "types-requests"
      database-dependencies:
        patterns:
          - "psycopg*"
          - "python-sql"
          - "sqlfluff"
      general-dependencies:
        patterns:
          - "pyyaml"
          - "simplejson"
          - "types-PyYAML"
          - "types-simplejson"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    assignees:
      - "luisa-beerboom"
