# join_models_yml.py is a temporary script to create the old models.yml until
# all services are able to work with the new separat collections.

from pathlib import Path

import yaml


def join_yaml_file(meta_file, collections_dir, output_file):
    result = {}

    with open(meta_file, "r", encoding="utf-8") as f:
        meta_data = yaml.safe_load(f)
        result["_meta"] = meta_data

    collections_path = Path(collections_dir)
    yaml_files = sorted(collections_path.glob("*.yml"))

    for yaml_file in yaml_files:
        with open(yaml_file, "r", encoding="utf-8") as f:
            data = yaml.safe_load(f)

            result[yaml_file.stem] = data

    with open(output_file, "w", encoding="utf-8") as f:
        f.write("# GENERATED FILE - DO NOT EDIT MANUALLY\n")
        f.write(
            "# This file is automatically generated. Manual changes will be overwritten.\n"
        )
        f.write("---\n")

        yaml.dump(
            result, f, default_flow_style=False, allow_unicode=True, sort_keys=False
        )


if __name__ == "__main__":
    try:
        join_yaml_file("collection-meta.yml", "collections", "models.yml")
    except Exception as e:
        print(f"Fehler: {e}")
